
# Project information
site_name: Calendar Boi Docs
site_url: https://github.com/CIIC4060-ICOM5016-FALL-2021/booking-system-pika
site_author: FrenzyExists, JuanGonzalezLopez, shulk72
site_description: >-
  Simple Google Calendar Clone, part of a project me 
  and the boys are taking at college.

nav:
    - Home: index.md
    - Diagram: diagram.md
theme: 
  name: material
  features:
    - navigation.top
  font:
    text: IBM Plex Sans
  logo: assets/calendar.svg
